apiVersion: operator.aquasec.com/v1alpha1
kind: AquaGateway
metadata:
  name: aqua
spec:
  infra:                                    
    serviceAccount: "aqua-sa"               
    version: "4.6"
  common:
    databaseSecret:                         
      name: "aqua-aqua-db"
      key: "password"     
  externalDb:                              
    host: "aqua-db"
    port: 5432
    username: postgres                      
  deploy:                                   
    replicas: 1                             
    service: "ClusterIP"