apiVersion: operator.aquasec.com/v1alpha1
kind: AquaGateway
metadata:
  name: aqua
spec:
  infra:                                    # Optional: Infrastructure information
    serviceAccount: "aqua-sa"               # Optional: auto generate if requirment is true
    version: "4.6"                          # Optional: auto generate if requirment is true to latest version
    platform: "openshift"                   # Optional: auto generate if requirment is true to openshift
  common:
    imagePullSecret:                        # Optional: if already created image pull secret then mention in here
    databaseSecret:                         # Optional: if already created database password secret
      key:
      name:
  externalDb:                               # Optional: if want to use external db and not internal database
    host:
    port:
    username:
    password:                               # Optional: if not using the common.databaseSecret
  deploy:                                   # Required: information about aqua gateway deployment
    replicas: 1                             # Required: number of replicas
    service: "ClusterIP"                    # Required: service type for aqua gateway
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "gateway"                 # Optional: if not given take the default value - gateway
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "4.6"                            # Optional: if not given take the default value - 4.5 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
