apiVersion: operator.aquasec.com/v1alpha1
kind: AquaScanner
metadata:
  name: aqua
spec:
  infra:                                    # Optional: Infrastructure information
    serviceAccount: "aqua-sa"               # Optional: auto generate if requirment is true
    version: "4.6"                          # Optional: auto generate if requirment is true to latest version
    platform: "openshift"                   # Optional: auto generate if requirment is true to openshift
  common:
    imagePullSecret:                        # Optional: if already created image pull secret then mention in here
  deploy:                                   # Required: information about aqua scanner deployment
    replicas: 1                             # Required: number of replicas
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "scanner"                 # Optional: if not given take the default value - scanner
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "4.6"                            # Optional: if not given take the default value - 4.5 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  login:                                    # Required: Information about login to aqua server for scanning
    username:
    password:
    host:
