apiVersion: operator.aquasec.com/v1alpha1
kind: AquaCsp
metadata:
  name: aqua
spec:
  infra:                                    # Optional: Infrastructure information
    serviceAccount: "aqua-sa"               # Optional: auto generate if requirment is true
    namespace: "aqua"                       # Optional: auto generate if requirment is true
    version: "6.2"                          # Optional: auto generate if requirment is true to latest version
    platform: "openshift"                   # Optional: auto generate if requirment is true to openshift
    requirements: true                      # Optional: default is false
  common:
    activeActive: false                     # Optional: if to work with cluster mode if you have more then 1 server, default false
    storageclass: "default"                 # Optional: if not given then use storage class default
    cybercenterAddress:                     # Optional: if not given then use default https://cybercenter.aquasec.com
    imagePullSecret:                        # Optional: if already created image pull secret then mention in here
    adminPassword:                          # Optional: if already created admin password secret
      key:
      name:
    license:                                # Optional: if already created license secret
      key:
      name:
    databaseSecret:                         # Optional: if already created database password secret
      key:
      name:
    dbDiskSize:                             # Optional: size of internal db pvc if not given use default value 10
    splitDB:                                # Optional: create 2 database deployments, one for audit and one for configuration
  externalDb:                               # Optional: if want to use external db and not internal database
    host:
    port:
    username:
    password:                               # Optional: if not using the common.databaseSecret
  auditDB:                                  # Optional: applied only when splitDB set to true. must be set when using externalDb
    information:
      host:
      port:
      username:
      password:                               # Optional: if not, generating a random password
    secret:                                   # Optional: the secret to use for audit-db. if secret not exist, create secret with audit-db.information.password
      key:
      name:
  registry:                                 # Optional: if not given secret in common.imagePullSecret
    url: "registry.aquasec.com"
    username: "example@company.com"
    password: ""
    email: "example@company.com"
  database:                                 # Required: information about aqua gateway deployment
    replicas: 1                             # Required: number of replicas
    service: "ClusterIP"                    # Required: service type for aqua server
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "database"                # Optional: if not given take the default value - database
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "6.2"                            # Optional: if not given take the default value - 4.6 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  gateway:                                  # Required: information about aqua gateway deployment
    replicas: 1                             # Required: number of replicas
    service: "ClusterIP"                    # Required: service type for aqua server
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "gateway"                 # Optional: if not given take the default value - gateway
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "6.2"                            # Optional: if not given take the default value - 4.6 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  server:                                   # Required: information about aqua server deployment
    replicas: 1                             # Required: number of replicas
    service: "LoadBalancer"                 # Required: service type for aqua server
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "server"                  # Optional: if not given take the default value - server
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "6.2"                            # Optional: if not given take the default value - 4.6 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  adminPassword:                            # Optional: Aqua Admin Password String
  licenseToken:                             # Optional: License Token String
  serverEnvs:                               # Optional: environment variables to add to the server (name:value)
  - name: "SOME ENV"
    value: "SOME ENV VALUE"
  - name: "ANOTHER ENV"
    value: "ANOTHER ENV VALUE"
  gatewayEnvs:                              # Optional: environment variables to add to the gateway (name:value)
  - name: "SOME ENV"
    value: "SOME ENV VALUE"
  - name: "ANOTHER ENV"
    value: "ANOTHER ENV VALUE"
  enforcer:                                 # Optional: Install also enforcer components
    enforceMode:                            # Optional: true/false if enforcer mode or audit
  route:                                    # Optional: true/false create route to aqua server and gateway services
  runAsNonRoot:                             # Optional: true/false
  kubeEnforcer:                             # Optional: Install also KubeEnforcer
    tag:                                    # Optional: KubeEnforcer image tag
    registry:                               # Optional: KubeEnforcer registry
