apiVersion: operator.aquasec.com/v1alpha1
kind: AquaServer
metadata:
  name: aqua
spec:
  infra:                                    # Optional: Infrastructure information
    serviceAccount: "aqua-sa"               # Optional: auto generate if requirment is true
    namespace: "aqua"                       # Optional: auto generate if requirment is true
    version: "2022.4"                       # Optional: auto generate if requirment is true to latest version
    platform: "openshift"                   # Optional: auto generate if requirment is true to openshift
  common:
    activeActive: false                     # Optional: to work in active active mode if you have more then 1 server, default false
    storageclass: "default"                 # Optional: if not given then use storage class default
    cybercenterAddress:                     # Optional: if not given then use default https://cybercenter.aquasec.com
    imagePullSecret:                        # Optional: if already created image pull secret then mention in here
    adminPassword:                          # Optional: if already created admin password secret
      key:
      name:
    license:                                # Optional: if already created license secret
      key:
      name:
    databaseSecret:                         # Optional: if already created database password secret
      key:
      name:
    splitDB:                                # Optional: create 2 database deployments, one for audit and one for configuration
  externalDb:                               # Optional: if want to use external db and not internal database
    host:
    port:
    username:
    password:                               # Optional: if not, generating a random password
  auditDB:                                  # Optional: applied only when splitDB set to true. must be set when using externalDb.
    information:
      host:
      port:
      username:
      password:                             # Optional: if not using the common.databaseSecret
    secret:                                 # Optional: the secret to use for audit-db. if secret not exist, create secret with audit-db.information.password
      key:
      name:
  deploy:                                   # Required: information about aqua server deployment
    replicas: 1                             # Required: number of replicas
    service: "LoadBalancer"                 # Required: service type for aqua server
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "server"                  # Optional: if not given take the default value - server
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "2022.4"                         # Optional: if not given take the default value - 4.5 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  adminPassword:                            # Optional: Aqua Admin Password String
  licenseToken:                             # Optional: License Token String
  runAsNonRoot:                             # Optional: true/false
  route:                                    # Optional: true/false
  configMapData:                          # Optional: configMap data to add to the server map[string]string
    key1: "value1"
    key2: "value2"