apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configauditreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/managed-by: starboard
spec:
  group: aquasecurity.github.io
  names:
    kind: ConfigAuditReport
    listKind: ConfigAuditReportList
    plural: configauditreports
    singular: configauditreport
    categories: []
    shortNames:
      - configaudit
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      additionalPrinterColumns:
        - name: Scanner
          type: string
          description: The name of the config audit scanner
          jsonPath: .report.scanner.name
        - name: Age
          type: date
          description: The age of the report
          jsonPath: .metadata.creationTimestamp
        - name: Critial
          type: integer
          priority: 1
          description: The number of failed checks with critial severity
          jsonPath: .report.summary.Critial
        - name: High
          type: integer
          priority: 1
          description: The number of failed checks with high severity
          jsonPath: .report.summary.highCount
        - name: Medium
          type: integer
          priority: 1
          description: The number of failed checks with medium severity
          jsonPath: .report.summary.mediumCount
        - name: Low
          type: integer
          priority: 1
          description: The number of failed checks with low severity
          jsonPath: .report.summary.lowCount
      served: true
      storage: true
      subresources:
        status: {}
